import Head from 'next/head'
import HomePage from '../containers/HomePage'
import styles from '../styles/Home.module.css'

const Home = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Github Profile Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {HomePage()}

    </div>
  )
}
export default Home;